cherry-pick the helm changes to release-1.3.x
Signed-off-by: Dhanendra Sahu <dhanendra.tech@gmail.com>

diff --git a/helm/regproc-pktserver/values.yaml b/helm/regproc-pktserver/values.yaml
--- a/helm/regproc-pktserver/values.yaml
+++ b/helm/regproc-pktserver/values.yaml
@@ -12,18 +12,23 @@
 ##
 commonLabels:
   app.kubernetes.io/component: mosip
+
 ## Add annotations to all the deployed resources
 ##
 commonAnnotations: {}
+
 ## Kubernetes Cluster Domain
 ##
 clusterDomain: cluster.local
+
 ## Extra objects to deploy (value evaluated as a template)
 ##
 extraDeploy: []
+
 ## Number of nodes
 ##
 replicaCount: 1
+
 service:
   type: ClusterIP
   port: 80
@@ -44,10 +49,11 @@ service:
   ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
   ##
   externalTrafficPolicy: Cluster
+
 image:
   registry: docker.io
   repository: mosipid/registration-processor-dmz-packet-server
-  tag: 1.3.0-beta.1
+  tag: 1.1.5.2
   ## Specify a imagePullPolicy
   ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
   ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
@@ -59,8 +65,10 @@ image:
   ##
   # pullSecrets:
   #   - myRegistryKeySecretName
+
 ## Port on which this particular spring service module is running.
 springServicePort: 8082
+
 ## Configure extra options for liveness and readiness probes
 ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
 ##
@@ -69,14 +77,20 @@ startupProbe:
   enabled: true
   exec:
     command:
-      - /bin/bash
-      - -c
-      - echo "regproc packet server is up !!!" > /home/mosip/landing/healthcheck.txt; url=http://localhost:8082/healthcheck.txt; curl_output="$(curl -w %{http_code} -o /dev/null -s $url)"; if ! [ "$curl_output" = "200" ]; then echo "$str failed with status code $curl_output" >> /dev/stderr && exit $i; fi;
+    - /bin/bash
+    - -c
+    - echo "regproc packet server is up !!!" > /home/mosip/landing/healthcheck.txt;
+      url=http://localhost:8082/healthcheck.txt;
+      curl_output="$(curl -w %{http_code} -o /dev/null -s $url)";
+      if ! [ "$curl_output" = "200" ]; then
+        echo "$str failed with status code $curl_output" >> /dev/stderr && exit $i;
+      fi;
   initialDelaySeconds: 0
   periodSeconds: 10
   timeoutSeconds: 5
   failureThreshold: 30
   successThreshold: 1
+
 livenessProbe:
   enabled: true
   httpGet:
@@ -87,6 +101,7 @@ livenessProbe:
   timeoutSeconds: 5
   failureThreshold: 6
   successThreshold: 1
+
 readinessProbe:
   enabled: true
   httpGet:
@@ -97,6 +112,7 @@ readinessProbe:
   timeoutSeconds: 5
   failureThreshold: 6
   successThreshold: 1
+
 ##
 # existingConfigmap:
 
@@ -104,10 +120,12 @@ readinessProbe:
 ##
 command: []
 args: []
+
 ## Deployment pod host aliases
 ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
 ##
 hostAliases: []
+
 ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
 ##
 resources:
@@ -119,33 +137,39 @@ resources:
     cpu: 500m
     memory: 1250Mi
   requests:
-    cpu: 100m
+    cpu: 500m
     memory: 100Mi
+
 additionalResources:
   ## Specify any JAVA_OPTS string here. These typically will be specified in conjunction with above resources
   ## Example: java_opts: "-Xms500M -Xmx500M"
-  javaOpts: "-Xms1000M -Xmx1000M"
+  javaOpts: "-Xms750M -Xmx750M"
+
 ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
 ## Clamav container already runs as 'mosip' user, so we may not need to enable this
 containerSecurityContext:
   enabled: false
   runAsUser: mosip
   runAsNonRoot: true
+
 ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
 ##
 podSecurityContext:
   enabled: false
   fsGroup: 1001
+
 ## Pod affinity preset
 ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
 ## Allowed values: soft, hard
 ##
 podAffinityPreset: ""
+
 ## Pod anti-affinity preset
 ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
 ## Allowed values: soft, hard
 ##
 podAntiAffinityPreset: soft
+
 ## Node affinity preset
 ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
 ## Allowed values: soft, hard
@@ -167,26 +191,32 @@ nodeAffinityPreset:
   ##   - e2e-az2
   ##
   values: []
+
 ## Affinity for pod assignment. Evaluated as a template.
 ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
 ##
 affinity: {}
+
 ## Node labels for pod assignment. Evaluated as a template.
 ## ref: https://kubernetes.io/docs/user-guide/node-selection/
 ##
 nodeSelector: {}
+
 ## Tolerations for pod assignment. Evaluated as a template.
 ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
 ##
 tolerations: []
+
 ## Pod extra labels
 ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
 ##
 podLabels: {}
+
 ## Annotations for server pods.
 ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
 ##
 podAnnotations: {}
+
 ##  pods' priority.
 ## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
 ##
@@ -194,13 +224,25 @@ podAnnotations: {}
 
 ## lifecycleHooks for the  container to automate configuration before or after startup.
 ##
-lifecycleHooks: {}
+lifecycleHooks:
+  preStop:
+    exec:
+      command:
+        - sh
+        - -c
+        - sleep 30
+
+## Termination grace period : the maximum amount of time (in seconds) Kubernetes will wait for a container to gracefully shut down
+terminationGracePeriodSeconds: 60
+
 ## Custom Liveness probes for
 ##
 customLivenessProbe: {}
+
 ## Custom Rediness probes
 ##
 customReadinessProbe: {}
+
 ## Update strategy - only really applicable for deployments with RWO PVs attached
 ## If replicas = 1, an update can get "stuck", as the previous pod remains attached to the
 ## PV, and the "incoming" pod can never start. Changing the strategy to "Recreate" will
@@ -208,6 +250,7 @@ customReadinessProbe: {}
 ##
 updateStrategy:
   type: RollingUpdate
+
 ## Additional environment variables to set
 ## Example:
 ## extraEnvVars:
@@ -215,21 +258,26 @@ updateStrategy:
 ##     value: "bar"
 ##
 extraEnvVars: []
+
 ## ConfigMap with extra environment variables that used
 ##
 extraEnvVarsCM:
   - global
   - config-server-share
   - artifactory-share
+
 ## Secret with extra environment variables
 ##
-extraEnvVarsSecret:
+extraEnvVarsSecret: []
+
 ## Extra volumes to add to the deployment
 ##
 extraVolumes: []
+
 ## Extra volume mounts to add to the container
 ##
 extraVolumeMounts: []
+
 ## Add init containers to the  pods.
 ## Example:
 ## initContainers:
@@ -241,6 +289,7 @@ extraVolumeMounts: []
 ##         containerPort: 1234
 ##
 initContainers: {}
+
 ## Add sidecars to the  pods.
 ## Example:
 ## sidecars:
@@ -252,6 +301,7 @@ initContainers: {}
 ##         containerPort: 1234
 ##
 sidecars: {}
+
 persistence:
   enabled: true
   ## If defined, storageClassName: <storageClass>
@@ -276,6 +326,7 @@ persistence:
   existingClaim: regproc-group1
   # Hardcoded in Dockerfile.
   mountDir: /home/mosip/landing
+
 ## Init containers parameters:
 ## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
 ##
@@ -283,8 +334,8 @@ volumePermissions:
   enabled: false
   image:
     registry: docker.io
-    repository: bitnami/bitnami-shell
-    tag: "10"
+    repository: mosipid/os-shell
+    tag: "12-debian-12-r46"
     pullPolicy: Always
     ## Optionally specify an array of imagePullSecrets.
     ## Secrets must be manually created in the namespace.
@@ -309,10 +360,12 @@ volumePermissions:
     ##   cpu: 100m
     ##   memory: 128Mi
     ##
+
 ## Specifies whether RBAC resources should be created
 ##
 rbac:
   create: true
+
 ## Specifies whether a ServiceAccount should be created
 ##
 serviceAccount:
@@ -321,6 +374,7 @@ serviceAccount:
   ## If not set and create is true, a name is generated using the fullname template
   ##
   name:
+
 ## Prometheus Metrics
 ##
 ## TODO: Enable when prometheus url is available
@@ -331,7 +385,9 @@ metrics:
   ##
   podAnnotations:
     prometheus.io/scrape: "true"
+
   endpointPath:
+
   ## Prometheus Service Monitor
   ## ref: https://github.com/coreos/prometheus-operator
   ##
@@ -358,6 +414,7 @@ metrics:
     ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
     ##
     additionalLabels: {}
+
   ## Custom PrometheusRule to be defined
   ## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
   ## ref: https://github.com/coreos/prometheus-operator#customresourcedefinitions
@@ -375,6 +432,7 @@ metrics:
     #     labels:
     #       severity: error
     rules: []
+
 ## pktserver does NOT require any external access.
 istio:
   enabled: false
